package gui;

import gameLogic.staff.Director;
import gameLogic.staff.interfaces.Employee;
import javax.swing.ImageIcon;
import utils.GuiHelper;

public class DirectorInfo<T extends Employee> extends javax.swing.JFrame {

  private final T todoPerson; // TODO T instead of Director
  private final Director person; // tmp

  public DirectorInfo(final Director person) {
    this.person = person;
    todoPerson = null;
    initComponents();
  }

  // <editor-fold desc="Auto">
  //
  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    directorIcon = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    separator0 = new javax.swing.JSeparator();
    staticLabel5 = new javax.swing.JLabel();
    overallLabel = new javax.swing.JLabel();
    staticLabel6 = new javax.swing.JLabel();
    salaryLabel = new javax.swing.JLabel();
    separator2 = new javax.swing.JSeparator();
    final javax.swing.JLabel staticLabel1 = new javax.swing.JLabel();
    influenceLabel = new javax.swing.JLabel();
    final javax.swing.JLabel staticLabel2 = new javax.swing.JLabel();
    managementLabel = new javax.swing.JLabel();
    final javax.swing.JLabel staticLabel3 = new javax.swing.JLabel();
    creativityLabel = new javax.swing.JLabel();
    final javax.swing.JLabel staticLabel4 = new javax.swing.JLabel();
    famaLabel = new javax.swing.JLabel();
    portraitLabel = new javax.swing.JLabel();
    sparator1 = new javax.swing.JSeparator();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Detalles de director");
    setBackground(new java.awt.Color(255, 255, 255));
    setForeground(new java.awt.Color(102, 102, 102));
    setType(java.awt.Window.Type.POPUP);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    directorIcon.setIcon(new javax.swing.ImageIcon("/Users/manutero/workspace/movie_maker/res/icons/director_s.png")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 10, 4, 10);
    getContentPane().add(directorIcon, gridBagConstraints);

    nameLabel.setBackground(new java.awt.Color(255, 255, 255));
    nameLabel.setFont(new java.awt.Font("Menlo", 0, 17)); // NOI18N
    nameLabel.setForeground(new java.awt.Color(102, 102, 102));
    nameLabel.setText(this.person.getName());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    getContentPane().add(nameLabel, gridBagConstraints);

    separator0.setForeground(javax.swing.UIManager.getDefaults().getColor("PropSheet.selectedSetBackground"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(separator0, gridBagConstraints);

    staticLabel5.setBackground(new java.awt.Color(255, 255, 255));
    staticLabel5.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    staticLabel5.setForeground(new java.awt.Color(102, 102, 102));
    staticLabel5.setText("Valoración general:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    getContentPane().add(staticLabel5, gridBagConstraints);

    overallLabel.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    overallLabel.setForeground(new java.awt.Color(102, 102, 102));
    overallLabel.setText(String.valueOf(this.person.getOverall()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    getContentPane().add(overallLabel, gridBagConstraints);

    staticLabel6.setBackground(new java.awt.Color(255, 255, 255));
    staticLabel6.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    staticLabel6.setForeground(new java.awt.Color(102, 102, 102));
    staticLabel6.setText("Salario mensual:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    getContentPane().add(staticLabel6, gridBagConstraints);

    salaryLabel.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    salaryLabel.setForeground(new java.awt.Color(102, 102, 102));
    salaryLabel.setText(String.valueOf(this.person.getSalary()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    getContentPane().add(salaryLabel, gridBagConstraints);

    separator2.setForeground(javax.swing.UIManager.getDefaults().getColor("PropSheet.selectedSetBackground"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(separator2, gridBagConstraints);

    staticLabel1.setBackground(new java.awt.Color(255, 255, 255));
    staticLabel1.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    staticLabel1.setForeground(new java.awt.Color(102, 102, 102));
    staticLabel1.setText("Influencia:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    getContentPane().add(staticLabel1, gridBagConstraints);

    influenceLabel.setBackground(new java.awt.Color(255, 255, 255));
    influenceLabel.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    influenceLabel.setForeground(new java.awt.Color(102, 102, 102));
    influenceLabel.setText(String.valueOf(this.person.getInfluenceRating()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    getContentPane().add(influenceLabel, gridBagConstraints);

    staticLabel2.setBackground(new java.awt.Color(255, 255, 255));
    staticLabel2.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    staticLabel2.setForeground(new java.awt.Color(102, 102, 102));
    staticLabel2.setText("Liderazgo:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    getContentPane().add(staticLabel2, gridBagConstraints);

    managementLabel.setBackground(new java.awt.Color(255, 255, 255));
    managementLabel.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    managementLabel.setForeground(new java.awt.Color(102, 102, 102));
    managementLabel.setText(String.valueOf(this.person.getManagementRating()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    getContentPane().add(managementLabel, gridBagConstraints);

    staticLabel3.setBackground(new java.awt.Color(255, 255, 255));
    staticLabel3.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    staticLabel3.setForeground(new java.awt.Color(102, 102, 102));
    staticLabel3.setText("Creatividad:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    getContentPane().add(staticLabel3, gridBagConstraints);

    creativityLabel.setBackground(new java.awt.Color(255, 255, 255));
    creativityLabel.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    creativityLabel.setForeground(new java.awt.Color(102, 102, 102));
    creativityLabel.setText(String.valueOf(this.person.getCreativeRating()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    getContentPane().add(creativityLabel, gridBagConstraints);

    staticLabel4.setBackground(new java.awt.Color(255, 255, 255));
    staticLabel4.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    staticLabel4.setForeground(new java.awt.Color(102, 102, 102));
    staticLabel4.setText("Fama:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    getContentPane().add(staticLabel4, gridBagConstraints);

    famaLabel.setBackground(new java.awt.Color(255, 255, 255));
    famaLabel.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
    famaLabel.setForeground(new java.awt.Color(102, 102, 102));
    famaLabel.setText(String.valueOf(this.person.getFamaRating()));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 10;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 0);
    getContentPane().add(famaLabel, gridBagConstraints);

    portraitLabel.setBackground(new java.awt.Color(255, 255, 255));
    portraitLabel.setFont(new java.awt.Font("Menlo", 0, 15)); // NOI18N
    portraitLabel.setForeground(new java.awt.Color(102, 102, 102));
    portraitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portraits/default_portrait.png"))); // NOI18N
    portraitLabel.setIcon(new ImageIcon(GuiHelper.getPortrait(this.person.getPortrait())));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.gridheight = 10;
    gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
    getContentPane().add(portraitLabel, gridBagConstraints);

    sparator1.setForeground(javax.swing.UIManager.getDefaults().getColor("PropSheet.selectedSetBackground"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 13;
    gridBagConstraints.gridwidth = 8;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(sparator1, gridBagConstraints);

    jButton1.setText("Seleccionar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 14;
    getContentPane().add(jButton1, gridBagConstraints);

    jButton2.setText("Cancelar");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 14;
    getContentPane().add(jButton2, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  public static void _main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DirectorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DirectorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DirectorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DirectorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new DirectorInfo(Director.createNewDirector("sin nombre")).setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel creativityLabel;
  private javax.swing.JLabel directorIcon;
  private javax.swing.JLabel famaLabel;
  private javax.swing.JLabel influenceLabel;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel managementLabel;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JLabel overallLabel;
  private javax.swing.JLabel portraitLabel;
  private javax.swing.JLabel salaryLabel;
  private javax.swing.JSeparator separator0;
  private javax.swing.JSeparator separator2;
  private javax.swing.JSeparator sparator1;
  private javax.swing.JLabel staticLabel5;
  private javax.swing.JLabel staticLabel6;
  // End of variables declaration//GEN-END:variables
  //
  // </editor-fold>
  
}
