package gui;

import controller.Controller;
import gameLogic.staff.Employee;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author manutero
 * @param <T>
 */
public class PopUp<T extends Employee> extends javax.swing.JFrame {

  private Controller controller;
  private final DefaultListModel avaibleChoices;

  /**
   * Creates new form PopUp for hiring staff.
   * In order to make it versatile, it's possible to create a new popUp containing
   * directors, scriptWriters, etc. 
   * <p>
   * @param <T>
   * @param candidates
   */
  public <T extends Employee> PopUp(final List<T> candidates) {
    this.avaibleChoices = createListModel(candidates);
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane2 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    selectionList = new javax.swing.JList();
    selectionButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Selección del Staff");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setPreferredSize(new java.awt.Dimension(264, 350));
    setResizable(false);
    setSize(new java.awt.Dimension(200, 350));
    setType(java.awt.Window.Type.POPUP);

    jSplitPane2.setDividerLocation(290);
    jSplitPane2.setDividerSize(3);
    jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    selectionList.setModel(this.avaibleChoices);
    selectionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(selectionList);

    jSplitPane2.setTopComponent(jScrollPane1);

    selectionButton.setText("Seleccionar");
    selectionButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectionButtonActionPerformed(evt);
      }
    });
    jSplitPane2.setBottomComponent(selectionButton);

    getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void selectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionButtonActionPerformed
    Object selected = avaibleChoices.get(selectionList.getSelectedIndex());
    controller.chosenStaff((T) selected);
    this.dispose();
  }//GEN-LAST:event_selectionButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane2;
  private javax.swing.JButton selectionButton;
  private javax.swing.JList selectionList;
  // End of variables declaration//GEN-END:variables

  // --------------------

  public void setController(Controller controller) {
    this.controller = controller;
  }

  private <T extends Employee> DefaultListModel createListModel(final List<T> list) {
    DefaultListModel response = new DefaultListModel();
    int i = 0;
    for (T element : list) {
      response.add(i, element);
    }
    return response;
  }

  // FiXME: delete this
  public void launch() {
    setVisible(true);
  }

}
